### ISSUE TITLE
Support for IProgress

### ISSUE THREAD

**Issue by slimshader** [kyubuns/AnimeTask#6]
Hi,

would it be possible to add animation progress support via IProgress interface? Progress would be normalized value (0..1), used like so:

```
await anime.Play([animation], Progress.Create<float>(x => { if (x > .05f) Debug.Log("After 50%);}))
```

**Comment by kyubuns** [comment]
Hi!

What you want to do can be achieved with the following code.

```csharp
await Anime.Play(Easing.Create<Linear>(0f, 1f, 2f), TranslateTo.Action<float>(x => { if (x > 0.5f) Debug.Log("After 50%"); }));
```

Or do you mean you want an alias that can write this in short?

**Comment by slimshader** [comment]
The point is to have access to progress values no matter what kind of animation is being played, how long it takes or what easing functions are used. So basically normalized (always 0..1) time of the “scrubber”. 

example use cases:
- fade value based on animation progress
- events triggered based on animation progress (similar to events fired on standard unity clip)

I suggested API based on standard IProgress<T> interface as both UniTask and UniRx already support it

**Comment by kyubuns** [comment]
I see.

I support IProgress.

```csharp
await Anime.Play(Easing.Create<Linear>(2f), Progress.Create<float>(x => Debug.Log(x)));

// new syntax
await Easing.Create<Linear>(2f).ToProgress(Progress.Create<float>(x => Debug.Log(x)));
```

https://github.com/kyubuns/AnimeTask/commit/1ca419ce1aa289efa1f4865ab4e071202717325b

Thank you for your idea.
